### PR TITLE
chore(setupproject):set up empty express bolier plate project with dotenv

### PR DESCRIPTION
**Pull request by munyanezaarmel**
chore(kafka): import babel and remove  es5 

- remove es5 line of code in index.js
- install and import babel package

[fixes #182201507]

### CODE REVIEW

**Review by bourgiworks — DISMISSED** [review]

**Review by uwishema11 — DISMISSED** [review]

**Review by Julienish14 — COMMENTED** [review]
The part of URL may be you can change it to altp-rwanda/elite...... change it to the group url

and some description can't be a bad ideal

**Comment by munyanezaarmel** [comment]
chore(kafka): create pull_request_template.md and add all folder developer need 

create a pull request template file
add all folders 
[fixes #182201507]

**Review by kalisaNkevin — COMMENTED** [review]
Checked.

**Review by kalisaNkevin — DISMISSED** [review]

**Review by ishimweeli — APPROVED** [review]
well done armel

**Review by Francoise02 — COMMENTED** [review]
Nice work!

**Review by Julienish14 — APPROVED** [review]
great

**Review by Ntare22 — APPROVED** [review]
Great work but I don't know why you included the passport dependency this early but make sure next time, you only include dependencies that you're currently using.

**Pull request merged**
