### PR TITLE
On successful registration, users should receive a JWT

### PR DESCRIPTION
**Pull request by kalisaNkevin**
#### What does this PR do?

This PR should register a new user.

#### How should this be manually tested?

1. Create a `.env` file and add your credentials following an example from the `.env.example` file
2. In your terminal, run the command `npm run migration`  
3. Run `npm start`
4. After connecting to the database, check the following endpoint in your postman;
- `POST` `/api/v1/user/register`

#### Any background context you want to provide?

1. All JavaScript is written in ES6 and it uses babel to transpire down to ES5.
2. The user should receive a token after a successful registration.

#### What are the relevant pivotal tracker stories?

#182201566

### CODE REVIEW

**Review by ishimweeli — DISMISSED** [review]
please squash commits    another than that well done  server is starting

**Review by ishimweeli — COMMENTED** [review]
!

**Review by bourgiworks — COMMENTED** [review]
you can add  description to your PR

**Review by Francoise02 — CHANGES_REQUESTED** [review]
Some packages were used but aren't displayed in the `package.json` file. Please consider adding `morgan` and `cors` packages.

**Review by Ntare22 — APPROVED** [review]
It's still showing conflicts.. please rebase correctly.

**Review by Ntare22 — CHANGES_REQUESTED** [review]
Please rebase again

**Review by Julienish14 — APPROVED** [review]

**Review by Francoise02 — APPROVED** [review]

**Review by ishimweeli — APPROVED** [review]
well done kevin. good job

**Review by uwishema11 — APPROVED** [review]

**Review by munyanezaarmel — APPROVED** [review]

**Review by Ntare22 — APPROVED** [review]

**Pull request merged**
