### PR TITLE
ch-connecting-to-db-182201508

### PR DESCRIPTION
**Pull request by ishimweeli**
it is used to connect to postgres db

after cloning a repo cd into it and RUN npm  start

all JavaScript are written in ES6 

https://www.pivotaltracker.com/n/projects/2569104/stories/182201508

### CODE REVIEW

**Review by ishimweeli — COMMENTED** [review]
please help me to review this

**Comment by munyanezaarmel** [comment]
Add a pivotal tracker Id on your branch name

**Review by munyanezaarmel — COMMENTED** [review]
Add pivotal tracker Id on your branch name

**Review by didasmbalanya — CHANGES_REQUESTED** [review]
Fix PR naming convention and squash commits

**Pull request closed without merging**
