### PR TITLE
Ch integrate coverallscodecoverage 182201512

### PR DESCRIPTION
**Pull request by uwishema11**
####What does this PR do?
integrate coveralls  code coverage
####how should this be manually tested?
after cloning a repo cd into it and  run npm run coverage

####any background context you want to provide?
all JavaScript are written in ES6 and it use babel to transpire down to ES5

####what are the relevant pivotal tracker stories?
#182201512

### CODE REVIEW

**Review by didasmbalanya — CHANGES_REQUESTED** [review]
Run the tests and take a screenshot of the code coverage and add to PR
Also add the coverage badge on the readme

**Review by ishimweeli — DISMISSED** [review]
well done

**Review by ishimweeli — DISMISSED** [review]
you remain without commit i think its what they wanted you to do

**Review by Julienish14 — DISMISSED** [review]

**Review by Francoise02 — DISMISSED** [review]

**Review by Ntare22 — CHANGES_REQUESTED** [review]
Please add the coveralls badge on the README.md file

**Review by ishimweeli — APPROVED** [review]
remember to squash

**Review by kalisaNkevin — APPROVED** [review]

**Review by kalisaNkevin — APPROVED** [review]

**Review by Ntare22 — APPROVED** [review]

**Pull request merged**
