### PR TITLE
Ch-connecting-to-db-182201508

### PR DESCRIPTION
**Pull request by ishimweeli**
#### What does this PR do?
it connect to postgres database using siquelize

#### how should this be manually tested?
after cloning a repo cd into it and RUN npm run migration

#### any background context you want to provide?
all JavaScript are written in ES6 and it use babel to transpire down to ES5

####what are the relevant pivotal tracker stories?
https://www.pivotaltracker.com/story/show/182201508

### CODE REVIEW

**Review by bourgiworks — DISMISSED** [review]
i

**Review by Francoise02 — DISMISSED** [review]

**Review by Francoise02 — COMMENTED** [review]
You have two similar branches, you can consider removing one.

**Review by munyanezaarmel — COMMENTED** [review]
Great job @ishimweeli but i can suggest to use sequelize cli while generating modal in index.js check well that path envConfig=require('../config/config.js') and try to use dirname and make sure you  set well NODE_ENV I don't see it in .env.example make sure you declared it in set it to development | production | test 
- in config file you declared development database as link and in index.js model you declared split it into database name ,username i can suggest you to use database name,port,host,password for development and your Procfile which will run your db in production I am still testing it i will get back to you otherwise great job

**Review by munyanezaarmel — DISMISSED** [review]

**Review by munyanezaarmel — COMMENTED** [review]
great job make a new line at the end of each file

**Review by Ntare22 — APPROVED** [review]

**Review by Francoise02 — APPROVED** [review]

**Pull request merged**
